### ISSUE TITLE
Removing BSD license notes and original author names from source files

### ISSUE THREAD

**Issue by bmagyar** [robotican/robotican#22]
Hello there,

I have accidentally stumbled across your repository and found a weird commit:
https://github.com/robotican/robotican/commit/2d90fe3ffcba0eab8288f10f38d4328cf5daeb2c#diff-11974c8966f0faf7eca31127f0ff30ac

Seeing your practice of maintaining a copy of half of ROS as part of your deployment process I suspect this is not the only occasion __you removed copyright licenses and original author credits__.

__This is illegal__

Please revert these commits and respect original authors in good open source spirit.

Note: I'm executing the "Ask Nicely First." point from [here](https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice).

**Comment by elhayra** [comment]
Thank you for your Message Mr. Magyar, 
We have reviewed your claim and found the need to rewrite the copyright licenses and original author credits.

We will also perform a wider scope inspection to make sure copyright licenses and original author credits are in accordance with Github Policy.

Regards,
RoboTiCan team.

**Comment by efernandez** [comment]
Thanks!
